with open('debug_page.html', 'r', encoding='utf-8') as f:
    html = f.read()
    print('HTML长度:', len(html))
    print('\n前1000字符:')
    print(html[:1000])
    print('\n检查关键词:')
    print('包含"验证": ', '验证' in html)
    print('包含"登录": ', '登录' in html)
    print('包含"拦截": ', '拦截' in html)
    print('包含"__INITIAL_STATE__": ', '__INITIAL_STATE__' in html)
    print('包含"window.__INITIAL_STATE__": ', 'window.__INITIAL_STATE__' in html)
